# Generated by Django 6.0.4 on 2026-05-01 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name_en', models.TextField()),
                ('name_fr', models.TextField(blank=True)),
                ('name_rw', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('name_en', models.TextField()),
                ('name_fr', models.TextField(blank=True)),
                ('name_rw', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('content_en', models.TextField()),
                ('content_fr', models.TextField(blank=True)),
                ('content_rw', models.TextField(blank=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='laws.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='laws.title'),
        ),
    ]
